#!/usr/bin/expect -f
# 捕获 WINCH 信号，并传递给 Spawned 出来的 Children，
# 这样 ssh 的 TTY 就能随着窗口 resize 而适应。
trap {
    set rows [stty rows]
    set cols [stty columns]
    stty rows $rows columns $cols < $spawn_out(slave,name)
} WINCH

set host [lindex $argv 0]
set port [lindex $argv 1]

set timeout 20
spawn telnet $host $port
match_max 100000

expect {
    "Escape character*"
    {
    	#send -- "echo 'Welcome to '`hostname`'. Enjoy with sshgo...'\n"
    }
}
interact
